# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 12:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('openc2_type', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=15)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=200)),
                ('actuators', models.ManyToManyField(to='reactor_relay.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='CybOXType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_message', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('upstream_respond_to', models.CharField(max_length=5000, null=True)),
                ('upstream_command_ref', models.CharField(max_length=100, null=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactor_relay.Capability')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactor_relay.JobStatus'),
        ),
        migrations.AddField(
            model_name='capability',
            name='requires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactor_relay.CybOXType'),
        ),
    ]
